# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PawgleiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PawgleiOS
  pod 'RxSwift'
  pod 'RxRelay'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'SnapKit'

end
